name: Build Windows x64 Simple

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Windows executable
      run: npm run make
      
    - name: Upload Windows .exe
      uses: actions/upload-artifact@v4
      with:
        name: roulette-windows-x64
        path: |
          out/make/squirrel.windows/x64/*.exe
          out/make/zip/win32/x64/*.zip
        retention-days: 7
