name: Build Linux x64 Simple

on:
  push:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install build tooling
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y rpm

      - name: Install dependencies
        run: npm ci

      - name: Build Linux packages
        run: npm run make

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: roulette-linux-x64
          path: |
            out/make/deb/x64/*.deb
            out/make/rpm/x64/*.rpm
          retention-days: 7
